openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: A simple API for managing todos
servers:
  - url: http://localhost:5000
paths:
  /api/todos:
    get:
      summary: Get all todos
      responses:
        "200":
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTodo"
      responses:
        "201":
          description: Todo created successfully
  /api/todos/{id}:
    put:
      summary: Update a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTodo"
      responses:
        "204":
          description: Todo updated successfully
    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Todo deleted successfully
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
    NewTodo:
      type: object
      properties:
        title:
          type: string
      required:
        - title
    UpdateTodo:
      type: object
      properties:
        completed:
          type: boolean
      required:
        - completed
